# Generated by Django 2.1.1 on 2019-12-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pregnant',
            new_name='not_show_age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gestation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex_of_child',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/ava.png', upload_to='media/% Y/% m/% d/'),
        ),
    ]
