# Generated by Django 2.1.1 on 2019-07-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deleted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
