# Generated by Django 2.1.1 on 2019-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20190729_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
