# Generated by Django 2.1.1 on 2019-09-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20190930_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='slug',
        ),
    ]
