# Generated by Django 2.1.1 on 2019-10-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20190930_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
