# Generated by Django 2.1.1 on 2019-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191203_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='not_show_age',
            new_name='hide_age',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
