# Generated by Django 2.1.1 on 2019-12-08 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning', models.BooleanField(blank=True, default=False, null=True)),
                ('pregnant', models.BooleanField(blank=True, default=False, null=True)),
                ('weeks', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('date_of_child', models.DateField(blank=True, null=True)),
                ('children', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
