# Generated by Django 2.1.1 on 2019-12-17 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_auto_20191208_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('child_date_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('child_description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('hospital', models.CharField(max_length=100, null=True)),
                ('home_birth', models.BooleanField(blank=True, default=False, null=True)),
                ('hospital_rating', models.IntegerField(default=0)),
                ('hospital_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
